services:
  web:
    build: .
    ports:
      - "8029:80"
    depends_on:
      - db
    networks:
      - webnet
    environment:
      DB_HOST: db  # Establecer variable de entorno para la base de datos

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Usar la variable de .env
      MYSQL_DATABASE: pweb1  # Usar la variable de .env
      MYSQL_USER: alumno  # Usar la variable de .env
      MYSQL_PASSWORD: pweb1  # Usar la variable de .env
    ports:
      - "3306:3306"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
