version: '3.8'
services:
  web:
    build: .
    ports:
      - "8028:80"
    depends_on:
      - db
    networks:
      - webnet
    environment:
      DB_HOST: db  # Establecer variable de entorno para la base de datos

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Usar la variable de .env
      MYSQL_DATABASE: ${MYSQL_DATABASE}  # Usar la variable de .env
      MYSQL_USER: ${MYSQL_USER}  # Usar la variable de .env
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  # Usar la variable de .env
    ports:
      - "3306:3306"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
