version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8076:80"
    volumes:
      - ./cgi-bin:/usr/lib/cgi-bin
      - ./css:/var/www/html/css
      - ./js:/var/www/html/js
      - ./index.html:/var/www/html/index.html
      - ./new.html:/var/www/html/new.html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: pweb1
      DB_USER: alumno
      DB_PASSWORD: pweb1

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3387:3306"

volumes:
  db_data:
