# Usa una imagen base de MariaDB
FROM mariadb:latest

# Establecer variables de entorno para la base de datos
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=pweb1
ENV MYSQL_USER=alumno
ENV MYSQL_PASSWORD=pweb1

# Copiar archivo init.sql al contenedor
COPY ./init.sql /docker-entrypoint-initdb.d/

# Establecer permisos adecuados para el archivo init.sql
RUN chmod 644 /docker-entrypoint-initdb.d/init.sql
