CREATE DATABASE IF NOT EXISTS pweb1;
USE pweb1;
CREATE TABLE IF NOT EXISTS Wiki (
    name VARCHAR(255) PRIMARY KEY,
    markdown TEXT
);
GRANT ALL PRIVILEGES ON pweb1.* TO 'alumno'@'%';
FLUSH PRIVILEGES;
