CREATE DATABASE IF NOT EXISTS pweb1;
USE pweb1;

CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(100) NOT NULL UNIQUE 
);

CREATE TABLE IF NOT EXISTS Articles (
    title VARCHAR(255) NOT NULL,      
    owner VARCHAR(100) NOT NULL,     
    text TEXT NOT NULL,              
    PRIMARY KEY (title, owner),      
    FOREIGN KEY (owner) REFERENCES Users(username) 
);


CREATE USER IF NOT EXISTS 'alumno'@'%' IDENTIFIED BY 'pweb1';
GRANT ALL PRIVILEGES ON pweb1.* TO 'alumno'@'%';
FLUSH PRIVILEGES;
